name: Build & Test Project

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet pack --configuration Release
      - run: dotnet test
      - run: dotnet nuget push $(ls -1t ./thomasjude.core/bin/Release/*.nupkg | head -n 1) --api-key $NUGET_PUBLISH_TOKEN --source https://api.nuget.org/v3/index.json
        env:
          NUGET_PUBLISH_TOKEN: ${{secrets.nuget_publish_token}}
      
