name: Build & Test Project

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use; x will use the latest version of the 3.1 channel
      - run: dotnet build --configuration Release
      - run: dotnet test
      - run: dotnet nuget push $(ls -1t ./thomasjude.core/bin/Release/*.nupkg | head -n 1) --api-key $NUGET_PUBLISH_TOKEN --source https://api.nuget.org/v3/index.json
        env:
          NUGET_PUBLISH_TOKEN: ${{secrets.nuget_publish_token}}
      # - run: ls -al ./thomasjude.core/bin/Release && echo "token - ${NUGET_PUBLISH_TOKEN} -"
      #   env:
      #     NUGET_PUBLISH_TOKEN: ${{secrets.nuget_publish_token}}
      
